installed_plugins:
 - { name: "ace-editor",  version: "1.1" }
 - { name: "active-directory",  version: "2.0" }
 - { name: "ant",  version: "1.4" }
 - { name: "antisamy-markup-formatter",  version: "1.5" }
 - { name: "artifactory",  version: "2.9.1" }
 - { name: "authentication-tokens",  version: "1.3" }
 - { name: "bouncycastle-api",  version: "2.16.0" }
 - { name: "branch-api",  version: "1.11.1" }
 - { name: "build-pipeline-plugin",  version: "1.5.6" }
 - { name: "build-timeout",  version: "1.18" }
 - { name: "cloudbees-folder",  version: "5.16" }
 - { name: "conditional-buildstep",  version: "1.3.5" }
 - { name: "config-file-provider",  version: "2.15.5" }
 - { name: "credentials-binding",  version: "1.10" }
 - { name: "credentials",  version: "2.1.11" }
 - { name: "display-url-api",  version: "1.1.1" }
 - { name: "docker-commons",  version: "1.6" }
 - { name: "docker-workflow",  version: "1.9.1" }
 - { name: "durable-task",  version: "1.13" }
 - { name: "email-ext",  version: "2.54" }
 - { name: "envinject",  version: "1.93.1" }
 - { name: "external-monitor-job",  version: "1.7" }
 - { name: "git-client",  version: "2.2.1" }
 - { name: "git",  version: "3.0.1" }
 - { name: "github-api",  version: "1.84" }
 - { name: "github-branch-source",  version: "1.10.1" }
 - { name: "github",  version: "1.25.1" }
 - { name: "github-organization-folder",  version: "1.5" }
 - { name: "git-server",  version: "1.7" }
 - { name: "gradle",  version: "1.25" }
 - { name: "handlebars",  version: "1.1.1" }
 - { name: "icon-shim",  version: "2.0.3" }
 - { name: "ivy",  version: "1.27.1" }
 - { name: "javadoc",  version: "1.4" }
 - { name: "jenkins-multijob-plugin",  version: "1.23" }
 - { name: "job-dsl",  version: "1.57" }
 - { name: "job-node-stalker",  version: "1.0.5" }
 - { name: "jquery-detached",  version: "1.2.1" }
 - { name: "jquery",  version: "1.11.2-0" }
 - { name: "junit",  version: "1.19" }
 - { name: "ldap",  version: "1.14" }
 - { name: "mailer",  version: "1.19" }
 - { name: "mapdb-api",  version: "1.0.9.0" }
 - { name: "matrix-auth",  version: "1.4" }
 - { name: "matrix-project",  version: "1.8" }
 - { name: "maven-plugin",  version: "2.14" }
 - { name: "momentjs",  version: "1.1.1" }
 - { name: "pam-auth",  version: "1.3" }
 - { name: "parameterized-trigger",  version: "2.32" }
 - { name: "pipeline-build-step",  version: "2.4" }
 - { name: "pipeline-graph-analysis",  version: "1.3" }
 - { name: "pipeline-input-step",  version: "2.5" }
 - { name: "pipeline-milestone-step",  version: "1.3" }
 - { name: "pipeline-model-api",  version: "1.0" }
 - { name: "pipeline-model-declarative-agent",  version: "1.0" }
 - { name: "pipeline-model-definition",  version: "1.0" }
 - { name: "pipeline-rest-api",  version: "2.4" }
 - { name: "pipeline-stage-step",  version: "2.2" }
 - { name: "pipeline-stage-tags-metadata",  version: "1.0" }
 - { name: "pipeline-stage-view",  version: "2.4" }
 - { name: "plain-credentials",  version: "1.3" }
 - { name: "resource-disposer",  version: "0.6" }
 - { name: "role-strategy",  version: "2.3.2" }
 - { name: "run-condition",  version: "1.0" }
 - { name: "scm-api",  version: "1.3" }
 - { name: "script-security",  version: "1.25" }
 - { name: "simple-theme-plugin",  version: "0.3" }
 - { name: "ssh-credentials",  version: "1.13" }
 - { name: "ssh-slaves",  version: "1.13" }
 - { name: "structs",  version: "1.5" }
 - { name: "subversion",  version: "2.7.1" }
 - { name: "timestamper",  version: "1.8.8" }
 - { name: "token-macro",  version: "2.0" }
 - { name: "windows-slaves",  version: "1.2" }
 - { name: "workflow-aggregator",  version: "2.5" }
 - { name: "workflow-api",  version: "2.8" }
 - { name: "workflow-basic-steps",  version: "2.3" }
 - { name: "workflow-cps-global-lib",  version: "2.5" }
 - { name: "workflow-cps",  version: "2.25" }
 - { name: "workflow-durable-task-step",  version: "2.8" }
 - { name: "workflow-job",  version: "2.9" }
 - { name: "workflow-multibranch",  version: "2.9.2" }
 - { name: "workflow-scm-step",  version: "2.3" }
 - { name: "workflow-step-api",  version: "2.8" }
 - { name: "workflow-support",  version: "2.12" }
 - { name: "ws-cleanup",  version: "0.32" }